config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :users

  resources :orders

  resources :line_items do
    member do
      post 'decrement'
    end
  end

  resources :carts

  get "store/index"
  
  resources :products do
    get :who_bought, on: :member
  end

  resources :products

  root :to => 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
<!-- START_HIGHLIGHT -->
  <title>Pragprog Books Online Store</title>
<!-- END_HIGHLIGHT -->
  <%= stylesheet_link_tag "application" %><!-- <label id="code.slt"/> -->
  <%= javascript_include_tag "application" %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
    	<% if @cart %>
    	<%= hidden_div_if(@cart.line_items.empty?,id: 'cart') do %>
        	<%= render @cart %>
        <% end %>
        <% end %>    	
        
      <ul>
        <li><%= link_to 'Home',   store_path   %></li>
        <li><a href="http://www..../faq">Questions</a></li>
        <li><a href="http://www..../news">News</a></li>
        <li><a href="http://www..../contact">Contact</a></li>
        <li>* * *</li>
        <li><%= Time.zone.now.to_formatted_s(:short) %></li>
      
      <% if session[:user_id] %>
        <br />
        <li><%= link_to 'Orders',   orders_path   %></li>
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users',    users_path    %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete   %>
      <% end %>
      </ul>

    </div>
    <div id="main">
<!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
<!-- START_HIGHLIGHT -->
    </div>
  </div>
<!-- END_HIGHLIGHT -->
</body>
</html>